variables:
  GKE_PROJECT: coinninja01
  GKE_INSTANCE: coinninja01
  GKE_ZONE: us-central1-c
  GKE_APP_TYPE: deployment
  DOCKER_TLS_CERTDIR: ""

# Login for git
before_script:
  - echo -e "machine git.coinninja.net\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > $HOME/.netrc

stages:
  - test
  - build
  - testing
  - production

test:
  stage: test
  image: golang:1.13-alpine3.10
  services:
    - name: postgres:9.6
      alias: postgresdb
  variables:
    POSTGRES_DB: thunderdome
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .cache
  script:
    - export STORAGE_HOST=${CI_SERVICE_HOST:-postgres} # Hack to fix kube runner
    - apk add --update-cache make git protobuf protobuf-dev curl
    - mkdir -p .cache
    - export GOPATH="$CI_PROJECT_DIR/.cache"
    - export PATH=$PATH:$GOPATH/bin
    - export GOPRIVATE=git.coinninja.net
    - timeout 60 sh -c 'until nc -z $0 $1; do sleep 1; done' $STORAGE_HOST 5432
    - CGO_ENABLED=0 make test

.build: &build
  allow_failure: false
  services:
    - docker:dind
  image: docker:stable
  before_script:
    - export DOCKER_HOST=${CI_SERVICE_HOST:-docker} # Hack to fix kube runner
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --build-arg CI_JOB_TOKEN=$CI_JOB_TOKEN --pull --tag $CONTAINER_NAME .
    - docker push $CONTAINER_NAME

build:branch:
  <<: *build
  stage: build
  variables:
    CONTAINER_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  when: manual
  only:
    - branches@backend/thunderdome
  except:
    - master
    - develop
    - tags

build:latest:
  <<: *build
  stage: build
  variables:
    CONTAINER_NAME: $CI_REGISTRY_IMAGE:latest
  only:
    - develop@backend/thunderdome

build:tagged:
  <<: *build
  stage: build
  variables:
    CONTAINER_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags@backend/thunderdome
  except:
    - branches

# Common k8s elements
.k8s: &k8s
  image: google/cloud-sdk:latest
  allow_failure: false
  before_script:
    - echo -n "${__k8s_prod_sa_key}" | base64 -d > /tmp/key.json
    - gcloud auth activate-service-account --key-file /tmp/key.json
    - gcloud config set project ${GKE_PROJECT}
    - gcloud config set compute/zone ${GKE_ZONE}
    - gcloud container clusters get-credentials ${GKE_INSTANCE}
    - kubectl config current-context
  script: |
    export CURRENT_IMAGE=$(kubectl -n ${CI_ENVIRONMENT_SLUG} get ${GKE_APP_TYPE} ${GKE_APP_NAME} -o=jsonpath='{$.spec.template.spec.containers[0].image}')
    if [[ "${CURRENT_IMAGE}" != "${CONTAINER_NAME}" ]]; then
      echo "current image '${CURRENT_IMAGE}' is not '${CONTAINER_NAME}'"
      kubectl -n ${CI_ENVIRONMENT_SLUG} set image ${GKE_APP_TYPE}/${GKE_APP_NAME} ${GKE_APP_NAME}=${CONTAINER_NAME} --record
    else
      echo "current image '${CURRENT_IMAGE}' is correct. Patching..."
      kubectl --namespace=${CI_ENVIRONMENT_SLUG} patch ${GKE_APP_TYPE} ${GKE_APP_NAME} -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}" --record
    fi
    kubectl -n ${CI_ENVIRONMENT_SLUG} rollout status ${GKE_APP_TYPE} ${GKE_APP_NAME} -w

testing:branch-server:
  <<: *k8s
  stage: testing
  environment:
    name: test
    url: https://api.${CI_ENVIRONMENT_SLUG}.coinninja.net/api/v1/thunderdome/version
  variables:
    CONTAINER_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    GKE_APP_NAME: thunderdome
  only:
    - branches@backend/thunderdome
  except:
    - master
    - develop

testing:branch-monitor:
  <<: *k8s
  stage: testing
  environment:
    name: test
    url: https://api.${CI_ENVIRONMENT_SLUG}.coinninja.net/api/v1/thunderdome/version
  variables:
    CONTAINER_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    GKE_APP_NAME: thunderdome-monitor
  only:
    - branches@backend/thunderdome
  except:
    - master
    - develop

testing:latest-server:
  <<: *k8s
  stage: testing
  environment:
    name: test
    url: https://api.${CI_ENVIRONMENT_SLUG}.coinninja.net/api/v1/thunderdome/version
  variables:
    CONTAINER_NAME: $CI_REGISTRY_IMAGE:latest
    GKE_APP_NAME: thunderdome
  only:
    - develop@backend/thunderdome

testing:latest-monitor:
  <<: *k8s
  stage: testing
  environment:
    name: test
    url: https://api.${CI_ENVIRONMENT_SLUG}.coinninja.net/api/v1/thunderdome/version
  variables:
    CONTAINER_NAME: $CI_REGISTRY_IMAGE:latest
    GKE_APP_NAME: thunderdome-monitor
  only:
    - develop@backend/thunderdome

testing:tag-server:
  <<: *k8s
  stage: testing
  environment:
    name: test
    url: https://api.${CI_ENVIRONMENT_SLUG}.coinninja.net/api/v1/thunderdome/version
  variables:
    CONTAINER_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    GKE_APP_NAME: thunderdome
  only:
    - tags@backend/thunderdome
  except:
    - branches

testing:tag-monitor:
  <<: *k8s
  stage: testing
  environment:
    name: test
    url: https://api.${CI_ENVIRONMENT_SLUG}.coinninja.net/api/v1/thunderdome/version
  variables:
    CONTAINER_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    GKE_APP_NAME: thunderdome-monitor
  only:
    - tags@backend/thunderdome
  except:
    - branches

production:tag-server:
  <<: *k8s
  stage: production
  environment:
    name: prod
    url: https://api.${CI_ENVIRONMENT_SLUG}.coinninja.net/api/v1/thunderdome/version
  variables:
    CONTAINER_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    GKE_APP_NAME: thunderdome
  when: manual
  only:
    - tags@backend/thunderdome
  except:
    - branches

production:tag-monitor:
  <<: *k8s
  stage: production
  environment:
    name: prod
    url: https://api.${CI_ENVIRONMENT_SLUG}.coinninja.net/api/v1/thunderdome/version
  variables:
    CONTAINER_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    GKE_APP_NAME: thunderdome-monitor
  when: manual
  only:
    - tags@backend/thunderdome
  except:
    - branches
