// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tdrpc/adminrpc.proto

package tdrpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// AdminAccountsRequest is used to request one or more accounts
type AdminAccountsRequest struct {
	// Filter values (id, address)
	Filter map[string]string `protobuf:"bytes,1,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Offset, Limit for pagination
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit  int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *AdminAccountsRequest) Reset()      { *m = AdminAccountsRequest{} }
func (*AdminAccountsRequest) ProtoMessage() {}
func (*AdminAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f27b1318c7cd0a2, []int{0}
}
func (m *AdminAccountsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminAccountsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminAccountsRequest.Merge(m, src)
}
func (m *AdminAccountsRequest) XXX_Size() int {
	return m.Size()
}
func (m *AdminAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminAccountsRequest proto.InternalMessageInfo

func (m *AdminAccountsRequest) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *AdminAccountsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *AdminAccountsRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type AdminAccountsResponse struct {
	// The list of accounts
	Accounts []*Account `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
}

func (m *AdminAccountsResponse) Reset()      { *m = AdminAccountsResponse{} }
func (*AdminAccountsResponse) ProtoMessage() {}
func (*AdminAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f27b1318c7cd0a2, []int{1}
}
func (m *AdminAccountsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminAccountsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminAccountsResponse.Merge(m, src)
}
func (m *AdminAccountsResponse) XXX_Size() int {
	return m.Size()
}
func (m *AdminAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminAccountsResponse proto.InternalMessageInfo

func (m *AdminAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

// Used to get an account
type AdminGetAccountRequest struct {
	// The id of the account
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The address of the account
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *AdminGetAccountRequest) Reset()      { *m = AdminGetAccountRequest{} }
func (*AdminGetAccountRequest) ProtoMessage() {}
func (*AdminGetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f27b1318c7cd0a2, []int{2}
}
func (m *AdminGetAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminGetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminGetAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminGetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminGetAccountRequest.Merge(m, src)
}
func (m *AdminGetAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *AdminGetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminGetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminGetAccountRequest proto.InternalMessageInfo

func (m *AdminGetAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AdminGetAccountRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AdminUpdateAccountRequest struct {
	// The id of the account
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The locked status of the account
	Locked bool `protobuf:"varint,2,opt,name=locked,proto3" json:"locked,omitempty"`
}

func (m *AdminUpdateAccountRequest) Reset()      { *m = AdminUpdateAccountRequest{} }
func (*AdminUpdateAccountRequest) ProtoMessage() {}
func (*AdminUpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f27b1318c7cd0a2, []int{3}
}
func (m *AdminUpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AdminUpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AdminUpdateAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AdminUpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUpdateAccountRequest.Merge(m, src)
}
func (m *AdminUpdateAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *AdminUpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUpdateAccountRequest proto.InternalMessageInfo

func (m *AdminUpdateAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AdminUpdateAccountRequest) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

func init() {
	proto.RegisterType((*AdminAccountsRequest)(nil), "tdrpc.AdminAccountsRequest")
	proto.RegisterMapType((map[string]string)(nil), "tdrpc.AdminAccountsRequest.FilterEntry")
	proto.RegisterType((*AdminAccountsResponse)(nil), "tdrpc.AdminAccountsResponse")
	proto.RegisterType((*AdminGetAccountRequest)(nil), "tdrpc.AdminGetAccountRequest")
	proto.RegisterType((*AdminUpdateAccountRequest)(nil), "tdrpc.AdminUpdateAccountRequest")
}

func init() { proto.RegisterFile("tdrpc/adminrpc.proto", fileDescriptor_5f27b1318c7cd0a2) }

var fileDescriptor_5f27b1318c7cd0a2 = []byte{
	// 572 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x41, 0x6f, 0xd3, 0x3e,
	0x18, 0xc6, 0xe3, 0xec, 0xbf, 0xfe, 0x87, 0xc7, 0x36, 0x66, 0x75, 0x25, 0x2b, 0xc3, 0x54, 0xb9,
	0x30, 0x0d, 0x96, 0x48, 0xe3, 0x02, 0xbb, 0xa0, 0x6d, 0x02, 0x2e, 0x3d, 0xa0, 0x48, 0x1c, 0xe0,
	0xe6, 0xc4, 0x6e, 0x66, 0x9a, 0xda, 0x21, 0x71, 0x40, 0x13, 0x42, 0x42, 0x7c, 0x02, 0x24, 0xbe,
	0x04, 0x1f, 0x83, 0x23, 0xc7, 0x4a, 0x5c, 0x76, 0xa4, 0x29, 0x07, 0x8e, 0xbb, 0x73, 0x41, 0x75,
	0x1c, 0x28, 0x6d, 0x05, 0x97, 0xd6, 0xcf, 0xfb, 0xd8, 0x3f, 0xbf, 0xef, 0xd3, 0x1a, 0x36, 0x15,
	0xcd, 0xd2, 0xc8, 0x27, 0x74, 0xc0, 0x45, 0x96, 0x46, 0x5e, 0x9a, 0x49, 0x25, 0xd1, 0xb2, 0xae,
	0xb6, 0x37, 0x2b, 0x53, 0x7f, 0x56, 0x4e, 0x7b, 0x27, 0x96, 0x32, 0x4e, 0x98, 0x4f, 0x52, 0xee,
	0x13, 0x21, 0xa4, 0x22, 0x8a, 0x4b, 0x91, 0x1b, 0x77, 0x3f, 0xe6, 0xea, 0xb4, 0x08, 0xbd, 0x48,
	0x0e, 0xfc, 0x58, 0xc6, 0xd2, 0xd7, 0xe5, 0xb0, 0xe8, 0x69, 0xa5, 0x85, 0x5e, 0x99, 0xed, 0xb7,
	0xf5, 0x57, 0xb4, 0x1f, 0x33, 0xb1, 0x9f, 0xbf, 0x22, 0x71, 0xcc, 0x32, 0x5f, 0xa6, 0x1a, 0x38,
	0x0f, 0x77, 0x3f, 0x01, 0xd8, 0x3c, 0x9a, 0xf4, 0x79, 0x14, 0x45, 0xb2, 0x10, 0x2a, 0x0f, 0xd8,
	0x8b, 0x82, 0xe5, 0x0a, 0xdd, 0x87, 0x8d, 0x1e, 0x4f, 0x14, 0xcb, 0x1c, 0xd0, 0x59, 0xda, 0x5d,
	0x3d, 0xb8, 0xe9, 0x55, 0x1d, 0x2f, 0xda, 0xec, 0x3d, 0xd4, 0x3b, 0x1f, 0x08, 0x95, 0x9d, 0x05,
	0xe6, 0x18, 0x6a, 0xc1, 0x86, 0xec, 0xf5, 0x72, 0xa6, 0x9c, 0xa5, 0x0e, 0xd8, 0x5d, 0x0e, 0x8c,
	0x42, 0x4d, 0xb8, 0x9c, 0xf0, 0x01, 0x57, 0xce, 0x7f, 0xba, 0x5c, 0x89, 0xf6, 0x3d, 0xb8, 0x3a,
	0x05, 0x41, 0x57, 0xe0, 0x52, 0x9f, 0x9d, 0x39, 0xa0, 0x03, 0x76, 0x2f, 0x05, 0x93, 0xe5, 0xe4,
	0xd8, 0x4b, 0x92, 0x14, 0xcc, 0xb1, 0x75, 0xad, 0x12, 0x87, 0xf6, 0x5d, 0xe0, 0x9e, 0xc0, 0xad,
	0x99, 0xa6, 0xf2, 0x54, 0x8a, 0x9c, 0xa1, 0x3d, 0xb8, 0x42, 0x4c, 0xcd, 0x0c, 0xb1, 0x5e, 0x0f,
	0x51, 0x95, 0x83, 0x5f, 0xbe, 0x7b, 0x0c, 0x5b, 0x1a, 0xf2, 0x88, 0xa9, 0xda, 0x34, 0x41, 0xac,
	0x43, 0x9b, 0x53, 0xd3, 0x89, 0xcd, 0x29, 0x72, 0xe0, 0xff, 0x84, 0xd2, 0x8c, 0xe5, 0xb9, 0x69,
	0xa5, 0x96, 0xee, 0x09, 0xdc, 0xd6, 0x8c, 0x27, 0x29, 0x25, 0x8a, 0xfd, 0x03, 0xd3, 0x82, 0x8d,
	0x44, 0x46, 0x7d, 0x46, 0x35, 0x65, 0x25, 0x30, 0xea, 0xe0, 0x87, 0x0d, 0x57, 0x34, 0x25, 0x78,
	0x7c, 0x82, 0x42, 0x78, 0xb9, 0xcb, 0xf3, 0xba, 0xa3, 0x1c, 0x5d, 0xfb, 0xcb, 0x8f, 0xd0, 0xde,
	0x59, 0x6c, 0x56, 0x61, 0xb8, 0x57, 0xdf, 0x7d, 0xf9, 0xf6, 0xc1, 0xde, 0x44, 0x1b, 0xd5, 0xdf,
	0xd2, 0xaf, 0x27, 0x47, 0x4f, 0x21, 0xfc, 0x3d, 0x34, 0xba, 0x3e, 0x0d, 0x99, 0x0b, 0xa3, 0x3d,
	0x13, 0xa0, 0xbb, 0xa3, 0xa9, 0x2d, 0xd4, 0x9c, 0xa1, 0xfa, 0xaf, 0x39, 0x7d, 0x83, 0x42, 0xb8,
	0xf6, 0x47, 0x16, 0xa8, 0x33, 0x4d, 0x5f, 0x14, 0xd3, 0xdc, 0x05, 0x37, 0xf4, 0x05, 0xdb, 0x07,
	0x0b, 0x2f, 0x38, 0x04, 0x7b, 0xa8, 0x0b, 0x1b, 0x5d, 0x46, 0x63, 0x96, 0xa1, 0xa6, 0x39, 0x5a,
	0xc9, 0x1a, 0xb8, 0x35, 0x53, 0x35, 0x71, 0x6c, 0x69, 0xee, 0x06, 0x5a, 0x33, 0xdc, 0x44, 0xdb,
	0xc7, 0x64, 0x38, 0xc2, 0xd6, 0xf9, 0x08, 0x5b, 0x17, 0x23, 0x0c, 0xde, 0x96, 0x18, 0x7c, 0x2c,
	0x31, 0xf8, 0x5c, 0x62, 0x30, 0x2c, 0x31, 0xf8, 0x5a, 0x62, 0xf0, 0xbd, 0xc4, 0xd6, 0x45, 0x89,
	0xad, 0xf7, 0x63, 0x6c, 0x0d, 0xc7, 0xd8, 0x3a, 0x1f, 0x63, 0xeb, 0xd9, 0xad, 0x98, 0x2b, 0x2f,
	0x92, 0x5c, 0x08, 0x2e, 0x9e, 0x13, 0x4f, 0x30, 0xe5, 0x87, 0x24, 0xea, 0x33, 0x41, 0x7d, 0x75,
	0x5a, 0x08, 0xca, 0x32, 0x2a, 0x07, 0xac, 0x7a, 0xf2, 0x61, 0x43, 0x3f, 0xbc, 0x3b, 0x3f, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x77, 0xb9, 0x33, 0x70, 0x25, 0x04, 0x00, 0x00,
}

func (this *AdminAccountsRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AdminAccountsRequest)
	if !ok {
		that2, ok := that.(AdminAccountsRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Filter) != len(that1.Filter) {
		return false
	}
	for i := range this.Filter {
		if this.Filter[i] != that1.Filter[i] {
			return false
		}
	}
	if this.Offset != that1.Offset {
		return false
	}
	if this.Limit != that1.Limit {
		return false
	}
	return true
}
func (this *AdminAccountsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AdminAccountsResponse)
	if !ok {
		that2, ok := that.(AdminAccountsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Accounts) != len(that1.Accounts) {
		return false
	}
	for i := range this.Accounts {
		if !this.Accounts[i].Equal(that1.Accounts[i]) {
			return false
		}
	}
	return true
}
func (this *AdminGetAccountRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AdminGetAccountRequest)
	if !ok {
		that2, ok := that.(AdminGetAccountRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Address != that1.Address {
		return false
	}
	return true
}
func (this *AdminUpdateAccountRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*AdminUpdateAccountRequest)
	if !ok {
		that2, ok := that.(AdminUpdateAccountRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Locked != that1.Locked {
		return false
	}
	return true
}
func (this *AdminAccountsRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&tdrpc.AdminAccountsRequest{")
	keysForFilter := make([]string, 0, len(this.Filter))
	for k, _ := range this.Filter {
		keysForFilter = append(keysForFilter, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForFilter)
	mapStringForFilter := "map[string]string{"
	for _, k := range keysForFilter {
		mapStringForFilter += fmt.Sprintf("%#v: %#v,", k, this.Filter[k])
	}
	mapStringForFilter += "}"
	if this.Filter != nil {
		s = append(s, "Filter: "+mapStringForFilter+",\n")
	}
	s = append(s, "Offset: "+fmt.Sprintf("%#v", this.Offset)+",\n")
	s = append(s, "Limit: "+fmt.Sprintf("%#v", this.Limit)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *AdminAccountsResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&tdrpc.AdminAccountsResponse{")
	if this.Accounts != nil {
		s = append(s, "Accounts: "+fmt.Sprintf("%#v", this.Accounts)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *AdminGetAccountRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&tdrpc.AdminGetAccountRequest{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "Address: "+fmt.Sprintf("%#v", this.Address)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *AdminUpdateAccountRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&tdrpc.AdminUpdateAccountRequest{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "Locked: "+fmt.Sprintf("%#v", this.Locked)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringAdminrpc(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AdminRPCClient is the client API for AdminRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminRPCClient interface {
	// List Accounts
	ListAccounts(ctx context.Context, in *AdminAccountsRequest, opts ...grpc.CallOption) (*AdminAccountsResponse, error)
	// Get Account
	GetAccount(ctx context.Context, in *AdminGetAccountRequest, opts ...grpc.CallOption) (*Account, error)
	// Update Account
	UpdateAccount(ctx context.Context, in *AdminUpdateAccountRequest, opts ...grpc.CallOption) (*Account, error)
	// Decode a payment request
	Ledger(ctx context.Context, in *LedgerRequest, opts ...grpc.CallOption) (*LedgerResponse, error)
}

type adminRPCClient struct {
	cc *grpc.ClientConn
}

func NewAdminRPCClient(cc *grpc.ClientConn) AdminRPCClient {
	return &adminRPCClient{cc}
}

func (c *adminRPCClient) ListAccounts(ctx context.Context, in *AdminAccountsRequest, opts ...grpc.CallOption) (*AdminAccountsResponse, error) {
	out := new(AdminAccountsResponse)
	err := c.cc.Invoke(ctx, "/tdrpc.AdminRPC/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRPCClient) GetAccount(ctx context.Context, in *AdminGetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/tdrpc.AdminRPC/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRPCClient) UpdateAccount(ctx context.Context, in *AdminUpdateAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/tdrpc.AdminRPC/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminRPCClient) Ledger(ctx context.Context, in *LedgerRequest, opts ...grpc.CallOption) (*LedgerResponse, error) {
	out := new(LedgerResponse)
	err := c.cc.Invoke(ctx, "/tdrpc.AdminRPC/Ledger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminRPCServer is the server API for AdminRPC service.
type AdminRPCServer interface {
	// List Accounts
	ListAccounts(context.Context, *AdminAccountsRequest) (*AdminAccountsResponse, error)
	// Get Account
	GetAccount(context.Context, *AdminGetAccountRequest) (*Account, error)
	// Update Account
	UpdateAccount(context.Context, *AdminUpdateAccountRequest) (*Account, error)
	// Decode a payment request
	Ledger(context.Context, *LedgerRequest) (*LedgerResponse, error)
}

func RegisterAdminRPCServer(s *grpc.Server, srv AdminRPCServer) {
	s.RegisterService(&_AdminRPC_serviceDesc, srv)
}

func _AdminRPC_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRPCServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tdrpc.AdminRPC/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRPCServer).ListAccounts(ctx, req.(*AdminAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRPC_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRPCServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tdrpc.AdminRPC/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRPCServer).GetAccount(ctx, req.(*AdminGetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRPC_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRPCServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tdrpc.AdminRPC/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRPCServer).UpdateAccount(ctx, req.(*AdminUpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminRPC_Ledger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LedgerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminRPCServer).Ledger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tdrpc.AdminRPC/Ledger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminRPCServer).Ledger(ctx, req.(*LedgerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tdrpc.AdminRPC",
	HandlerType: (*AdminRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAccounts",
			Handler:    _AdminRPC_ListAccounts_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _AdminRPC_GetAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _AdminRPC_UpdateAccount_Handler,
		},
		{
			MethodName: "Ledger",
			Handler:    _AdminRPC_Ledger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tdrpc/adminrpc.proto",
}

func (m *AdminAccountsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminAccountsRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Filter) > 0 {
		for k, _ := range m.Filter {
			dAtA[i] = 0xa
			i++
			v := m.Filter[k]
			mapSize := 1 + len(k) + sovAdminrpc(uint64(len(k))) + 1 + len(v) + sovAdminrpc(uint64(len(v)))
			i = encodeVarintAdminrpc(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintAdminrpc(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintAdminrpc(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if m.Offset != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintAdminrpc(dAtA, i, uint64(m.Offset))
	}
	if m.Limit != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintAdminrpc(dAtA, i, uint64(m.Limit))
	}
	return i, nil
}

func (m *AdminAccountsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminAccountsResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Accounts) > 0 {
		for _, msg := range m.Accounts {
			dAtA[i] = 0xa
			i++
			i = encodeVarintAdminrpc(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *AdminGetAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminGetAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAdminrpc(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if len(m.Address) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintAdminrpc(dAtA, i, uint64(len(m.Address)))
		i += copy(dAtA[i:], m.Address)
	}
	return i, nil
}

func (m *AdminUpdateAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AdminUpdateAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintAdminrpc(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if m.Locked {
		dAtA[i] = 0x10
		i++
		if m.Locked {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func encodeVarintAdminrpc(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *AdminAccountsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Filter) > 0 {
		for k, v := range m.Filter {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovAdminrpc(uint64(len(k))) + 1 + len(v) + sovAdminrpc(uint64(len(v)))
			n += mapEntrySize + 1 + sovAdminrpc(uint64(mapEntrySize))
		}
	}
	if m.Offset != 0 {
		n += 1 + sovAdminrpc(uint64(m.Offset))
	}
	if m.Limit != 0 {
		n += 1 + sovAdminrpc(uint64(m.Limit))
	}
	return n
}

func (m *AdminAccountsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Accounts) > 0 {
		for _, e := range m.Accounts {
			l = e.Size()
			n += 1 + l + sovAdminrpc(uint64(l))
		}
	}
	return n
}

func (m *AdminGetAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovAdminrpc(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovAdminrpc(uint64(l))
	}
	return n
}

func (m *AdminUpdateAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovAdminrpc(uint64(l))
	}
	if m.Locked {
		n += 2
	}
	return n
}

func sovAdminrpc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozAdminrpc(x uint64) (n int) {
	return sovAdminrpc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *AdminAccountsRequest) String() string {
	if this == nil {
		return "nil"
	}
	keysForFilter := make([]string, 0, len(this.Filter))
	for k, _ := range this.Filter {
		keysForFilter = append(keysForFilter, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForFilter)
	mapStringForFilter := "map[string]string{"
	for _, k := range keysForFilter {
		mapStringForFilter += fmt.Sprintf("%v: %v,", k, this.Filter[k])
	}
	mapStringForFilter += "}"
	s := strings.Join([]string{`&AdminAccountsRequest{`,
		`Filter:` + mapStringForFilter + `,`,
		`Offset:` + fmt.Sprintf("%v", this.Offset) + `,`,
		`Limit:` + fmt.Sprintf("%v", this.Limit) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AdminAccountsResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AdminAccountsResponse{`,
		`Accounts:` + strings.Replace(fmt.Sprintf("%v", this.Accounts), "Account", "Account", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AdminGetAccountRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AdminGetAccountRequest{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`Address:` + fmt.Sprintf("%v", this.Address) + `,`,
		`}`,
	}, "")
	return s
}
func (this *AdminUpdateAccountRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&AdminUpdateAccountRequest{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`Locked:` + fmt.Sprintf("%v", this.Locked) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringAdminrpc(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *AdminAccountsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminAccountsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminAccountsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Filter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdminrpc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Filter == nil {
				m.Filter = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAdminrpc
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAdminrpc
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthAdminrpc
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthAdminrpc
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAdminrpc
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthAdminrpc
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthAdminrpc
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipAdminrpc(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthAdminrpc
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Filter[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAdminrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminAccountsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminAccountsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminAccountsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAdminrpc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Accounts = append(m.Accounts, &Account{})
			if err := m.Accounts[len(m.Accounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAdminrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminGetAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminGetAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminGetAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminrpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminrpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAdminrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AdminUpdateAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAdminrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AdminUpdateAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AdminUpdateAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAdminrpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Locked", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAdminrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Locked = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipAdminrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAdminrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAdminrpc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAdminrpc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAdminrpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAdminrpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAdminrpc
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthAdminrpc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowAdminrpc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipAdminrpc(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthAdminrpc
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthAdminrpc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAdminrpc   = fmt.Errorf("proto: integer overflow")
)
